version: 2

conda:
  environment: docs/environment.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-4.7"
#    python: "mambaforge-4.10"
  
# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Explicitly set the version of Python and its requirements
python:
  version: 3.9
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

